services:
  core-fe:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production  # ← Override ở đây
        
    image: corefe-core-fe:latest
    container_name: core-fe
    ports:
      - "4000:4000"
    restart: unless-stopped